### PR TITLE
Update dependencies and devDependencies

### PR DESCRIPTION
**Pull request by shinnn**
- I updated [rocambole-node-update](https://github.com/sindresorhus/rocambole-node-update) and [rocambole](https://github.com/millermedeiros/rocambole).
- I added test for ES6 code.
  - [rocambole v0.5.0 supports ES6](https://github.com/millermedeiros/rocambole/commit/32595d678e3df52ca2831056fc450f46529d4df8).

### CODE REVIEW

**Comment by pwmckenna** [comment]
very cool, thanks

**Comment by pwmckenna** [comment]
i'm not super familiar with the effect of bumping the node update dep. does this warrant a minor or patch version bump?

**Comment by shinnn** [comment]
This change requires at least minor version bump. Or, I think you can publish it as v1.0.0 since [the dep](https://github.com/sindresorhus/rocambole-node-update) is v1.0.0.

**Comment by pwmckenna** [comment]
just published as version 1.0.0. thanks again

**Comment by shinnn** [comment]
No problem :)

**Pull request merged**
